stages:
  - staging
  - production

.deploy: &deploy_template
  image: node:lts
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .wrangler/
  before_script:
    - yarn install
    - cp $WRANGLER_CONFIG wrangler.toml
  script:
    - yarn deploy --env $CI_ENVIRONMENT_NAME

staging:
  <<: *deploy_template
  stage: staging
  environment:
    name: staging
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

production:
  <<: *deploy_template
  stage: production
  environment:
    name: production
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
